apiVersion: v1
kind: Service
metadata:
  name: ezfastfood-payment-service
spec:
  type: ClusterIP # External communication
  selector:
    app: ezfastfood-payment-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
